<?php

namespace KeycloakBundle\Tests\api;

use Faker\Factory;
use Faker\Generator;
use KeycloakBundle\Keycloak\Configuration\Abstraction\ConfigurationInterface;
use KeycloakBundle\Keycloak\DTO\Common\Collections\Realization\Credentials;
use KeycloakBundle\Keycloak\DTO\Common\Credential\Realization\Password;
use KeycloakBundle\Keycloak\DTO\Common\Email;
use KeycloakBundle\Keycloak\DTO\Common\Name;
use KeycloakBundle\Keycloak\DTO\Common\Username;
use KeycloakBundle\Keycloak\DTO\Common\Uuid4;
use KeycloakBundle\Keycloak\DTO\User\Request\Authorization\Realization\ClientCredentials;
use KeycloakBundle\Keycloak\DTO\User\Request\SignUp\Realization\UserRepresentation;
use KeycloakBundle\Keycloak\DTO\User\Response\Authorization\SuccessAuthorization;
use KeycloakBundle\Keycloak\UseCase\Authorization\Realization\AuthorizationManager;
use KeycloakBundle\Keycloak\UseCase\UserManagement\Realization\UserManager;
use KeycloakBundle\Tests\KeycloakTestingKernel;
use PHPUnit\Framework\TestCase;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpKernel\KernelInterface;

final class UserManagementTest extends WebTestCase
{
    private static UserRepresentation $currentUser;
    private static Generator $faker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        self::$kernel = new KeycloakTestingKernel([
            'http_client' => [
                'base_uri' => $_ENV['KEYCLOAK_AUTH_URL']
            ],
            'realms' => [
                'test_realm' => [
                    'realmName' => $_ENV['KEYCLOAK_REALM'],
                    'connections' => [
                        'firstStub' => [
                            'clientId' => $_ENV['KEYCLOAK_CLIENT_ID'],
                            'clientSecret' => $_ENV['KEYCLOAK_CLIENT_SECRET'],
                            'admin' => false
                        ],
                        'secondStub' => [
                            'clientId' => $_ENV['KEYCLOAK_ADMIN_CLIENT_ID'],
                            'clientSecret' => $_ENV['KEYCLOAK_ADMIN_CLIENT_SECRET'],
                            'admin' => true
                        ]
                    ]
                ]
            ]
        ]);

        self::$kernel->boot();
    }

    /**
     * @beforeClass
     */
    public static function setupCurrentUserDTO()
    {
        UserManagementTest::$faker = Factory::create();

        self::$currentUser = new UserRepresentation(
            Uuid4::fromString(self::$faker->uuid),
            new Username(self::$faker->userName),
            new Email(self::$faker->email),
            new Credentials([new Password(self::$faker->password, false)]),
            true,
            new Name(self::$faker->firstName, self::$faker->lastName)
        );
    }

    public function testSignUp()
    {
        $container = self::$kernel->getContainer();
        $authorizationManager = $container->get(UserManager::class);
        self::assertInstanceOf(UserManager::class, $authorizationManager);

        $result = $authorizationManager->addUser(self::$currentUser);
        self::assertTrue($result);
    }

    public function testGetUserId()
    {
        $container = self::$kernel->getContainer();
        $authorizationManager = $container->get(UserManager::class);
        self::assertInstanceOf(UserManager::class, $authorizationManager);

        $id = $authorizationManager->getId(self::$currentUser->getEmail());
        self::assertNotNull($id);
    }

    public function testGetIdAndDelete()
    {
        $container = self::$kernel->getContainer();
        $authorizationManager = $container->get(UserManager::class);
        self::assertInstanceOf(UserManager::class, $authorizationManager);

        $uuid = $authorizationManager->getId(self::$currentUser->getEmail());

        $authorizationManager->deleteUser($uuid);
    }

    /**
     * @covers AuthorizationManager::login()
     */
    public function testLoginByClientCredentials()
    {
        $container = self::$kernel->getContainer();
        $authorizationManager = $container->get(AuthorizationManager::class);
        self::assertInstanceOf(AuthorizationManager::class, $authorizationManager);

        $token = $authorizationManager->login(new ClientCredentials(
           $_ENV['KEYCLOAK_ADMIN_CLIENT_ID'],
           $_ENV['KEYCLOAK_ADMIN_CLIENT_SECRET']
        ));

        self::assertInstanceOf(SuccessAuthorization::class, $token);
    }

    protected function tearDown(): void
    {
        $dir = self::$kernel->getCacheDir();
        $it = new RecursiveDirectoryIterator($dir, RecursiveDirectoryIterator::SKIP_DOTS);
        $files = new RecursiveIteratorIterator($it, RecursiveIteratorIterator::CHILD_FIRST);
        foreach($files as $file) {
            if ($file->isDir()){
                rmdir($file->getRealPath());
            } else {
                unlink($file->getRealPath());
            }
        }
        rmdir($dir);
    }
}